export type Modality = "en-vivo" | "online" | "hibrido";

export interface CourseModule {
  titulo: string;
  descripcion: string;
  duracion: string;
}

export interface CourseCategory {
  id: string;
  label: string;
  description: string;
  image: string;
}

export interface Course {
  slug: string;
  titulo: string;
  categoria: string;
  categoriaLabel: string;
  modalidad: Modality;
  horas: number;
  nivel: "Iniciación" | "Intermedio" | "Avanzado";
  badge?: string | null;
  image?: string;
  // Campos detallados opcionales (para uso futuro)
  modulos?: number;
  lecciones?: number;
  idioma?: string;
  instructor?: string;
  instructorBio?: string;
  color?: string;
  iconColor?: string;
  initials?: string;
  descripcionCorta?: string;
  descripcionLarga?: string[];
  aprenderas?: string[];
  dirigido?: string[];
  requisitos?: string[];
  contenido?: CourseModule[];
  incluye?: string[];
  contactEmail?: string;
}

// ─── Categorías ──────────────────────────────────────────────────────────────

export const CATEGORIES: CourseCategory[] = [
  {
    id: "recursos-humanos",
    label: "Recursos Humanos",
    description: "Reclutamiento, selección, clima laboral, desempeño y gestión del talento.",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "capacitacion",
    label: "Capacitación",
    description: "Formación de instructores, fundamentos pedagógicos y adiestramiento.",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "liderazgo",
    label: "Liderazgo",
    description: "Comunicación asertiva, motivación y desarrollo de habilidades directivas.",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "desarrollo-organizacional",
    label: "Desarrollo Organizacional",
    description: "Alta dirección, coaching, planeación estratégica, emprendimiento e innovación.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "gestion-calidad",
    label: "Gestión de Calidad",
    description: "Auditorías, normatividad ISO, procesos de producción y manuales.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "administracion-finanzas",
    label: "Administración y Finanzas",
    description: "Control interno, gestión financiera, compras e inventarios.",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "proyectos-licitaciones",
    label: "Proyectos y Licitaciones",
    description: "Gestión, supervisión y contratación de proyectos y licitaciones públicas.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "ventas-atencion-cliente",
    label: "Ventas y Atención al Cliente",
    description: "Estrategia publicitaria, servicio al cliente y sistemas de venta efectiva.",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "normatividad",
    label: "Normatividad",
    description: "Protección civil, NOM-035, LFT, IMSS y cumplimiento regulatorio.",
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "comercio-internacional",
    label: "Comercio Internacional",
    description: "Trámites aduanales, importaciones, exportaciones y legislación de adquisiciones.",
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=600&auto=format&fit=crop&q=70",
  },
  {
    id: "tecnologia-digital",
    label: "Tecnología Digital",
    description: "Transformación digital, sitios web, analítica de datos, IA y ciberseguridad.",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&auto=format&fit=crop&q=70",
  },
];

// ─── Cursos ───────────────────────────────────────────────────────────────────

export const COURSES: Course[] = [

  // ── RECURSOS HUMANOS (18) ────────────────────────────────────────────────

  {
    slug: "relaciones-laborales",
    titulo: "Relaciones Laborales",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "online",
    horas: 14,
    nivel: "Iniciación",
    modulos: 6,
    lecciones: 18,
    idioma: "Español",
    badge: null,
    instructor: "Equipo Kyoszen",
    instructorBio: "Abogados laborales y consultores de RRHH con experiencia en contratación, relaciones colectivas y cumplimiento de la Ley Federal del Trabajo.",
    color: "#EAE0FB",
    iconColor: "var(--color-blue)",
    initials: "RL",
    descripcionCorta: "Define los conceptos de empresa, patrón, trabajador y relación laboral, identificando tipos de contratos, duración y manera de demostrar la relación laboral.",
    descripcionLarga: [
      "Al finalizar el curso definirás de manera clara los conceptos de empresa, establecimiento, patrón, trabajador, relación laboral, clases de contratos laborales y clases de trabajadores.",
      "Identificarás los tipos de relaciones de trabajo, su duración, estructura, elementos y la manera de demostrar la relación laboral cuando no hay contrato de trabajo formal.",
    ],
    aprenderas: [
      "Definir relación de trabajo y sus elementos fundamentales",
      "Estructurar contratos individuales de trabajo",
      "Diferenciar contratos por tiempo determinado, indeterminado y por obra",
      "Identificar sujetos: trabajador, patrón, patrón sustituto, intermediario",
      "Distinguir conceptos legales de empresa y establecimiento",
      "Aplicar relaciones laborales estratégicas en la organización",
    ],
    dirigido: ["Encargados de RRHH y nóminas", "Emprendedores y dueños de negocio", "Jefes que contratan personal", "Estudiantes de derecho y administración"],
    requisitos: ["Sin requisitos previos"],
    contenido: [
      { titulo: "Relación de trabajo", descripcion: "Concepto y fundamento legal · Elementos de la relación de trabajo.", duracion: "2 h" },
      { titulo: "Contrato individual de trabajo", descripcion: "Concepto y fundamento legal · Elementos · Presunción de la existencia del contrato.", duracion: "2.5 h" },
      { titulo: "Duración de la relación laboral", descripcion: "Tiempo determinado · Tiempo indeterminado · Por obra · Prórroga del contrato.", duracion: "2.5 h" },
      { titulo: "Sujetos que intervienen", descripcion: "Trabajador · Patrón · Patrón sustituto · Intermediario.", duracion: "2 h" },
      { titulo: "Empresa y establecimiento", descripcion: "Concepto y fundamento legal de la empresa · Concepto y fundamento legal del establecimiento.", duracion: "2.5 h" },
      { titulo: "Relaciones laborales estratégicas", descripcion: "Función y objetivo principal · Reformulación de las relaciones laborales.", duracion: "2.5 h" },
    ],
    incluye: ["Constancia con validez oficial DC-3", "Plantillas de contratos individuales", "Guía rápida de LFT aplicada a PYMEs", "Sesiones de dudas legales"],
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "asesoria-capacitacion-rrhh",
    titulo: "Asesoría y Capacitación en Recursos Humanos",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 18,
    nivel: "Iniciación",
    badge: "Popular",
    descripcionCorta: "Conocimientos generales del área de Recursos Humanos: reclutamiento, selección, psicometría, evaluación, capacitación y desarrollo aplicados al contexto mexicano.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "desarrollo-capital-humano",
    titulo: "Desarrollo de Capital Humano y Mano de Obra",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "descripcion-puesto",
    titulo: "Descripción de Puesto",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "diseno-perfil-puestos",
    titulo: "Diseño de Perfil y Descripción de Puestos",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "planes-carrera-competencia",
    titulo: "Diseño y Desarrollo de Planes de Carrera por Sucesión por Competencia",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "entrevista-laboral-competencias",
    titulo: "Entrevista Laboral Profunda por Competencias",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "evaluacion-desempeno-360",
    titulo: "Evaluación de Desempeño 360 Grados",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "tabuladores-sueldos",
    titulo: "Generación de Tabuladores de Sueldos",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "herramientas-rh-productividad",
    titulo: "Herramientas de RH para Mejorar la Productividad",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "manejo-relaciones-laborales",
    titulo: "Manejo de Relaciones Laborales",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "manual-seleccion-entrevista",
    titulo: "Manual para la Selección de Personal Mediante Entrevista Profunda",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "online",
    horas: 10,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "medicion-clima-laboral",
    titulo: "Medición de Clima Laboral",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "organigrama",
    titulo: "Organigrama",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "plan-vida-carrera",
    titulo: "Plan de Vida y Carrera para Personal",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "programa-evaluacion-desempeno",
    titulo: "Programa de Evaluación de Desempeño",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "psicometria-laboral",
    titulo: "Psicometría Laboral",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 14,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "reclutamiento-3-0-competencias",
    titulo: "Reclutamiento 3.0 por Competencias",
    categoria: "recursos-humanos",
    categoriaLabel: "Recursos Humanos",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── CAPACITACIÓN (4) ─────────────────────────────────────────────────────

  {
    slug: "adiestramiento-prestacion-servicios",
    titulo: "Adiestramiento de la Prestación de Servicios",
    categoria: "capacitacion",
    categoriaLabel: "Capacitación",
    modalidad: "en-vivo",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "formacion-instructores-capacitacion",
    titulo: "Formación de Instructores de Capacitación",
    categoria: "capacitacion",
    categoriaLabel: "Capacitación",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "fundamentos-capacitacion-linea",
    titulo: "Fundamentos Legales Pedagógicos e Instrumentación de Capacitación en Línea",
    categoria: "capacitacion",
    categoriaLabel: "Capacitación",
    modalidad: "online",
    horas: 14,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "cursos-materiales-motivacion",
    titulo: "Cursos y Materiales de Motivación",
    categoria: "capacitacion",
    categoriaLabel: "Capacitación",
    modalidad: "hibrido",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── LIDERAZGO (4) ────────────────────────────────────────────────────────

  {
    slug: "comunicacion-asertiva",
    titulo: "Líneas de Comunicación Asertiva",
    categoria: "liderazgo",
    categoriaLabel: "Liderazgo",
    modalidad: "online",
    horas: 14,
    nivel: "Iniciación",
    badge: null,
    instructor: "Equipo Kyoszen",
    descripcionCorta: "Incrementa tus conocimientos sobre comunicación y pon en práctica habilidades asertivas, tanto en el ámbito personal como profesional.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "motivacion",
    titulo: "Motivación",
    categoria: "liderazgo",
    categoriaLabel: "Liderazgo",
    modalidad: "hibrido",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "liderazgo-rrhh",
    titulo: "Liderazgo y RRHH",
    categoria: "liderazgo",
    categoriaLabel: "Liderazgo",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "desarrollo-habilidades-jefes-gerentes",
    titulo: "Desarrollo de Habilidades para Jefes y Gerentes",
    categoria: "liderazgo",
    categoriaLabel: "Liderazgo",
    modalidad: "hibrido",
    horas: 24,
    nivel: "Intermedio",
    badge: "Popular",
    instructor: "Equipo Kyoszen",
    descripcionCorta: "Aplica los principios y técnicas de Administración y Liderazgo, usando las prácticas del Coaching, para mejorar la productividad y el desempeño de tus colaboradores.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── DESARROLLO ORGANIZACIONAL (9, incluye Emprendimiento e Innovación) ───

  {
    slug: "asesoria-organizacion-estructura-negocios",
    titulo: "Asesoría para la Organización y Estructura de Negocios",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 22,
    nivel: "Intermedio",
    badge: "Nuevo",
    descripcionCorta: "Identifica la relación e influencia de la Alta Dirección en el óptimo desarrollo de un Plan de Negocio.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "alta-direccion",
    titulo: "Alta Dirección",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Avanzado",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "asesoria-alta-direccion-planeacion",
    titulo: "Asesoría de Alta Dirección para la Planeación de Negocios",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 20,
    nivel: "Avanzado",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "como-hacer-negocio",
    titulo: "Cómo Hacer un Negocio",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Iniciación",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "gestion-negocios",
    titulo: "Gestión de Negocios",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 18,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "planeacion-estrategia",
    titulo: "Planeación y Estrategia",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "proceso-organizacional",
    titulo: "Proceso Organizacional",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "entrenamiento-coaching",
    titulo: "Servicio de Entrenamiento Coaching",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "en-vivo",
    horas: 20,
    nivel: "Avanzado",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "emprendimiento-innovacion",
    titulo: "Emprendimiento e Innovación",
    categoria: "desarrollo-organizacional",
    categoriaLabel: "Desarrollo Organizacional",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Iniciación",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── GESTIÓN DE CALIDAD (8) ───────────────────────────────────────────────

  {
    slug: "auditoria-interna",
    titulo: "Auditoría Interna",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: "Popular",
    descripcionCorta: "Conoce la metodología necesaria para la realización de auditorías internas basadas en la normatividad actual.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "atencion-no-conformidades-sgc",
    titulo: "Acciones para la Atención de No Conformidades y Solventación de Auditorías del SGC",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "en-vivo",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "medicion-indicadores-sgc",
    titulo: "Medición de Resultados e Indicadores de Desempeño del Sistema de Gestión de Calidad",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "formacion-auditores-internos",
    titulo: "Taller de Formación de Auditores Internos",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 20,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "formacion-auditores-iso",
    titulo: "Taller de Formación de Auditores ISO",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 24,
    nivel: "Avanzado",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "diagrama-flujo-cronograma",
    titulo: "Diagrama de Flujo y Cronograma de Actividades",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "online",
    horas: 16,
    nivel: "Iniciación",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "manuales-procedimiento",
    titulo: "Taller de Elaboración de Manuales de Procedimiento",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "taller-procesos-produccion",
    titulo: "Taller de Procesos de Producción",
    categoria: "gestion-calidad",
    categoriaLabel: "Gestión de Calidad",
    modalidad: "hibrido",
    horas: 20,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── ADMINISTRACIÓN Y FINANZAS (7) ────────────────────────────────────────

  {
    slug: "control-interno",
    titulo: "Control Interno",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "hibrido",
    horas: 20,
    nivel: "Intermedio",
    badge: null,
    descripcionCorta: "Adquiere los principios fundamentales del control interno y desarrolla habilidades para evaluarlo, diseñarlo y documentarlo.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "sistema-control-interno",
    titulo: "Sistema de Control Interno",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "control-interno-gestion-proyectos",
    titulo: "Control Interno como Herramienta de Gestión de Proyectos",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "estructuracion-sistema-control-interno",
    titulo: "Taller de Estructuración de Sistema de Control Interno",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "en-vivo",
    horas: 16,
    nivel: "Avanzado",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "revision-financiera",
    titulo: "Primer Avance Revisión Financiera",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "hibrido",
    horas: 8,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "gestion-financiera-proyectos",
    titulo: "Gestión Financiera de Proyectos",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "ejecucion-inventarios",
    titulo: "Guía para la Correcta Ejecución de Inventarios",
    categoria: "administracion-finanzas",
    categoriaLabel: "Administración y Finanzas",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── PROYECTOS Y LICITACIONES (7) ─────────────────────────────────────────

  {
    slug: "garantia-contratacion-proyectos",
    titulo: "Garantía en los Procedimientos de Contratación y Adjudicación de Proyectos",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "gestion-licitaciones",
    titulo: "Gestión de Licitaciones",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "licitaciones",
    titulo: "Licitaciones",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "documentacion-propuestas",
    titulo: "Integración de Documentación para Presentación de Propuestas",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "procesos-contratacion-adjudicaciones",
    titulo: "Procesos de Contratación, Aclaraciones y Adjudicaciones de Proyectos",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "supervision-proyectos",
    titulo: "Supervisión de Proyectos",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "taller-gestion-administracion-proyectos",
    titulo: "Taller de Gestión y Administración de Proyectos",
    categoria: "proyectos-licitaciones",
    categoriaLabel: "Proyectos y Licitaciones",
    modalidad: "hibrido",
    horas: 20,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── VENTAS Y ATENCIÓN AL CLIENTE (4) ─────────────────────────────────────

  {
    slug: "estrategia-publicitaria",
    titulo: "Estrategia Publicitaria",
    categoria: "ventas-atencion-cliente",
    categoriaLabel: "Ventas y Atención al Cliente",
    modalidad: "hibrido",
    horas: 14,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "poder-servir-cliente",
    titulo: "El Poder de Saber Servir al Cliente",
    categoria: "ventas-atencion-cliente",
    categoriaLabel: "Ventas y Atención al Cliente",
    modalidad: "en-vivo",
    horas: 8,
    nivel: "Iniciación",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "sistema-venta-efectiva",
    titulo: "Sistema de Venta Efectiva",
    categoria: "ventas-atencion-cliente",
    categoriaLabel: "Ventas y Atención al Cliente",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "promocion",
    titulo: "Promoción",
    categoria: "ventas-atencion-cliente",
    categoriaLabel: "Ventas y Atención al Cliente",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── NORMATIVIDAD (6) ─────────────────────────────────────────────────────

  {
    slug: "asesoria-riesgo-trabajo",
    titulo: "Asesoría en Riesgo de Trabajo",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "hibrido",
    horas: 18,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "plan-salud",
    titulo: "Plan de Salud",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "hibrido",
    horas: 8,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "proteccion-civil",
    titulo: "Protección Civil",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "en-vivo",
    horas: 20,
    nivel: "Iniciación",
    badge: null,
    descripcionCorta: "Elabora e instrumenta un Programa Interno de Protección Civil para mitigar riesgos, organizar brigadas y saber qué hacer antes, durante y después de una emergencia.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "ley-federal-trabajo",
    titulo: "Ley Federal del Trabajo",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "online",
    horas: 16,
    nivel: "Iniciación",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "nom-035",
    titulo: "NOM-035",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "en-vivo",
    horas: 16,
    nivel: "Intermedio",
    badge: "Popular",
    descripcionCorta: "Analiza el plan de trabajo, métodos, herramientas y acciones para el cumplimiento de la NOM-035 y la identificación de factores de riesgo psicosocial.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "seguridad-social",
    titulo: "Seguridad Social",
    categoria: "normatividad",
    categoriaLabel: "Normatividad",
    modalidad: "online",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── COMERCIO INTERNACIONAL (3) ───────────────────────────────────────────

  {
    slug: "legislacion-importaciones",
    titulo: "Legislación de Importaciones",
    categoria: "comercio-internacional",
    categoriaLabel: "Comercio Internacional",
    modalidad: "online",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "tramites-aduanales",
    titulo: "Trámites Aduanales",
    categoria: "comercio-internacional",
    categoriaLabel: "Comercio Internacional",
    modalidad: "online",
    horas: 16,
    nivel: "Iniciación",
    badge: "Nuevo",
    descripcionCorta: "Conoce los trámites, procedimientos y documentos necesarios para llevar a cabo una importación y/o exportación según las necesidades de tu negocio.",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "normatividad-adquisicion-publica",
    titulo: "La Normatividad de las Adquisiciones en la Adquisición Pública",
    categoria: "comercio-internacional",
    categoriaLabel: "Comercio Internacional",
    modalidad: "hibrido",
    horas: 12,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },

  // ── TECNOLOGÍA DIGITAL (5) ───────────────────────────────────────────────

  {
    slug: "sitio-web-sin-programacion",
    titulo: "Diseño y Construcción de un Sitio Web sin Programación",
    categoria: "tecnologia-digital",
    categoriaLabel: "Tecnología Digital",
    modalidad: "online",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "transformacion-digital-pyme",
    titulo: "Qué es la Transformación Digital y Cómo Aplicarla a una PYME",
    categoria: "tecnologia-digital",
    categoriaLabel: "Tecnología Digital",
    modalidad: "online",
    horas: 8,
    nivel: "Iniciación",
    badge: "Popular",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "estrategia-gestion-digital",
    titulo: "Estrategia y Gestión Digital",
    categoria: "tecnologia-digital",
    categoriaLabel: "Tecnología Digital",
    modalidad: "hibrido",
    horas: 16,
    nivel: "Intermedio",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "analitica-datos-ia",
    titulo: "Curso de Analítica, Datos e Inteligencia Artificial",
    categoria: "tecnologia-digital",
    categoriaLabel: "Tecnología Digital",
    modalidad: "online",
    horas: 20,
    nivel: "Intermedio",
    badge: "Nuevo",
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
  {
    slug: "ciberseguridad-pymes",
    titulo: "Ciberseguridad para PYMEs",
    categoria: "tecnologia-digital",
    categoriaLabel: "Tecnología Digital",
    modalidad: "online",
    horas: 12,
    nivel: "Iniciación",
    badge: null,
    contactEmail: "rsalazar@kyoszen.com.mx",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return COURSES.find((c) => c.slug === slug);
}

export const MODALITY_LABELS: Record<Modality, string> = {
  "en-vivo": "En vivo",
  "online": "Online a tu ritmo",
  "hibrido": "Híbrido",
};

export const MODALITY_BADGE: Record<Modality, string> = {
  "en-vivo": "bg-red-100 text-red-700",
  "online": "bg-green-soft text-[#15803d]",
  "hibrido": "bg-purple-soft text-purple",
};
