export type Job = {
  id: number;
  titulo: string;
  empresa: string;
  categoria: string;
  ubicacion: string;
  contrato: string;
  jornada: string;
  salario: number;
  badge: string;
  badgeClass: string;
  desc: string;
  tags: string[];
  responsabilidades: string[];
  requisitos: string[];
};

export const JOBS: Job[] = [
  {
    id: 1,
    titulo: "Auxiliar Administrativo",
    empresa: "Grupo Corpora",
    categoria: "Administrativo",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 12000,
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    desc: "Apoyo en gestion documental, atencion a clientes internos y manejo de agenda ejecutiva.",
    tags: ["Office 365", "Atencion al cliente", "Organizacion"],
    responsabilidades: [
      "Gestion y archivo de documentos fisicos y digitales",
      "Atencion a clientes internos y proveedores",
      "Manejo de agenda y coordinacion de reuniones",
      "Elaboracion de reportes y minutas",
      "Control de correspondencia y paqueteria",
    ],
    requisitos: [
      "Preparatoria terminada o carrera tecnica en Administracion",
      "Manejo intermedio de Office 365 (Word, Excel, Outlook)",
      "Experiencia minima de 6 meses en puesto similar",
      "Buena organizacion y atencion al detalle",
      "Disponibilidad de horario matutino",
    ],
  },
  {
    id: 2,
    titulo: "Operador de Almacen",
    empresa: "Logistica Norte",
    categoria: "Operaciones",
    ubicacion: "Estado de Mexico",
    contrato: "Tiempo completo",
    jornada: "Mixta",
    salario: 10000,
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    desc: "Control de inventarios, recepcion y despacho de mercancia, manejo de montacargas.",
    tags: ["Inventarios", "Montacargas", "Logistica"],
    responsabilidades: [
      "Recepcion, clasificacion y despacho de mercancia",
      "Control y actualizacion de inventarios en sistema",
      "Operacion de montacargas y equipo de carga",
      "Verificacion de condiciones de almacenamiento",
      "Elaboracion de reportes de entradas y salidas",
    ],
    requisitos: [
      "Secundaria terminada (preparatoria deseable)",
      "Licencia de montacargas vigente",
      "Experiencia minima de 1 año en almacen o logistica",
      "Capacidad para cargar hasta 25 kg",
      "Disponibilidad para jornada mixta",
    ],
  },
  {
    id: 3,
    titulo: "Ejecutivo de Ventas",
    empresa: "Sigma Retail",
    categoria: "Ventas",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 18000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Prospeccion, seguimiento y cierre de ventas B2B. Manejo de CRM y cumplimiento de metas.",
    tags: ["Ventas B2B", "CRM", "Negociacion"],
    responsabilidades: [
      "Prospeccion y generacion de nuevos clientes B2B",
      "Seguimiento puntual a oportunidades de venta",
      "Cierre de negociaciones y elaboracion de propuestas",
      "Mantenimiento y actualizacion del CRM",
      "Cumplimiento de metas mensuales de venta",
    ],
    requisitos: [
      "Licenciatura en Administracion, Mercadotecnia o afin",
      "Experiencia minima de 2 años en ventas B2B",
      "Manejo de CRM (HubSpot, Salesforce o similar)",
      "Habilidades de negociacion y comunicacion",
      "Auto propio (deseable)",
    ],
  },
  {
    id: 4,
    titulo: "Recepcionista",
    empresa: "Clinica Vitalis",
    categoria: "Atencion al cliente",
    ubicacion: "CDMX",
    contrato: "Medio tiempo",
    jornada: "Vespertina",
    salario: 8000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Atencion presencial y telefonica, coordinacion de citas y gestion de correspondencia.",
    tags: ["Atencion al cliente", "Multitareas", "Comunicacion"],
    responsabilidades: [
      "Atencion presencial y telefonica a pacientes y visitantes",
      "Coordinacion y agendamiento de citas medicas",
      "Gestion de correspondencia y paqueteria",
      "Mantenimiento del area de recepcion en orden",
      "Apoyo administrativo al equipo medico",
    ],
    requisitos: [
      "Preparatoria terminada",
      "Excelente presentacion y trato al publico",
      "Experiencia minima de 6 meses en recepcion o atencion al cliente",
      "Manejo basico de herramientas de oficina",
      "Disponibilidad en horario vespertino (14:00 a 20:00)",
    ],
  },
  {
    id: 5,
    titulo: "Coordinador de RRHH",
    empresa: "Grupo Corpora",
    categoria: "RRHH",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 22000,
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    desc: "Gestion de nomina, reclutamiento, capacitacion y relaciones laborales en empresa en crecimiento.",
    tags: ["Nomina", "Reclutamiento", "Relaciones laborales"],
    responsabilidades: [
      "Administracion y procesamiento de nomina quincenal",
      "Reclutamiento y seleccion de personal operativo y administrativo",
      "Diseño e implementacion de programas de capacitacion",
      "Gestion de relaciones laborales y clima organizacional",
      "Cumplimiento de obligaciones legales laborales (IMSS, INFONAVIT, SAT)",
    ],
    requisitos: [
      "Licenciatura en Administracion, Psicologia o Relaciones Industriales",
      "Experiencia minima de 3 años en puesto similar",
      "Conocimiento de Ley Federal del Trabajo y normatividad laboral",
      "Manejo de sistemas de nomina (NOI, SUA o similar)",
      "Liderazgo, organizacion y comunicacion efectiva",
    ],
  },
  {
    id: 6,
    titulo: "Vendedor de Campo",
    empresa: "Sigma Retail",
    categoria: "Ventas",
    ubicacion: "Estado de Mexico",
    contrato: "Tiempo completo",
    jornada: "Flexible",
    salario: 15000,
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    desc: "Visitas a clientes, presentacion de productos y seguimiento posventa en zona Edomex.",
    tags: ["Ventas externas", "Zona Edomex", "Prospectos"],
    responsabilidades: [
      "Visitas programadas a clientes actuales y prospectos",
      "Presentacion y demostracion de productos en punto de venta",
      "Levantamiento de pedidos y seguimiento posventa",
      "Cobertura de ruta asignada en zona Estado de Mexico",
      "Reporte diario de actividades y resultados",
    ],
    requisitos: [
      "Preparatoria terminada (licenciatura deseable)",
      "Experiencia minima de 1 año en ventas de campo o ruta",
      "Licencia de conducir vigente y auto propio",
      "Conocimiento de la zona Estado de Mexico",
      "Disponibilidad para horario flexible y trabajo en campo",
    ],
  },
  {
    id: 7,
    titulo: "Auxiliar Contable",
    empresa: "Finanzas MX",
    categoria: "Administrativo",
    ubicacion: "Hibrido",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 13000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Registro de operaciones contables, conciliaciones bancarias y elaboracion de reportes financieros.",
    tags: ["Contabilidad", "SAP", "Excel avanzado"],
    responsabilidades: [
      "Registro de polizas contables y operaciones diarias",
      "Conciliaciones bancarias mensuales",
      "Elaboracion de reportes financieros y estados de cuenta",
      "Apoyo en declaraciones fiscales y cierre mensual",
      "Archivo y organizacion de documentacion contable",
    ],
    requisitos: [
      "Licenciatura en Contaduria o Finanzas (pasante o titulado)",
      "Manejo intermedio-avanzado de Excel",
      "Experiencia con SAP, CONTPAQi o sistema contable similar",
      "Experiencia minima de 1 año en area contable",
      "Conocimientos basicos de normatividad fiscal mexicana",
    ],
  },
  {
    id: 8,
    titulo: "Agente de Servicio al Cliente",
    empresa: "Contact Nova",
    categoria: "Atencion al cliente",
    ubicacion: "Remoto",
    contrato: "Por proyecto",
    jornada: "Flexible",
    salario: 9500,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Atencion a clientes via chat, correo y telefono. Resolucion de incidencias y seguimiento de casos.",
    tags: ["Zendesk", "Servicio al cliente", "Remoto"],
    responsabilidades: [
      "Atencion a clientes por chat, correo electronico y telefono",
      "Resolucion de incidencias y quejas en primer contacto",
      "Seguimiento y documentacion de casos en Zendesk",
      "Escalamiento de casos complejos al area correspondiente",
      "Cumplimiento de metricas de calidad y tiempo de respuesta",
    ],
    requisitos: [
      "Preparatoria terminada",
      "Experiencia minima de 6 meses en atencion al cliente o call center",
      "Manejo basico de Zendesk o plataforma de tickets (deseable)",
      "Buena redaccion y comunicacion verbal",
      "Equipo de computo propio y conexion a internet estable",
    ],
  },
];

export function getJobById(id: number): Job | undefined {
  return JOBS.find((j) => j.id === id);
}
