export type Job = {
  id: number;
  titulo: string;
  empresa: string;
  categoria: string;
  ubicacion: string;
  contrato: string;
  jornada: string;
  salario: number;
  badge: string;
  badgeClass: string;
  desc: string;
  tags: string[];
  responsabilidades: string[];
  requisitos: string[];
};

export const JOBS: Job[] = [
  {
    id: 1,
    titulo: "Auxiliar Administrativo",
    empresa: "Grupo Corpora",
    categoria: "Administrativo",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 12000,
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    desc: "Apoyo en gestión documental, atención a clientes internos y manejo de agenda ejecutiva.",
    tags: ["Office 365", "Atención al cliente", "Organización"],
    responsabilidades: [
      "Gestión y archivo de documentos físicos y digitales",
      "Atención a clientes internos y proveedores",
      "Manejo de agenda y coordinación de reuniones",
      "Elaboración de reportes y minutas",
      "Control de correspondencia y paquetería",
    ],
    requisitos: [
      "Preparatoria terminada o carrera técnica en Administración",
      "Manejo intermedio de Office 365 (Word, Excel, Outlook)",
      "Experiencia mínima de 6 meses en puesto similar",
      "Buena organización y atención al detalle",
      "Disponibilidad de horario matutino",
    ],
  },
  {
    id: 2,
    titulo: "Operador de Almacén",
    empresa: "Logística Norte",
    categoria: "Operaciones",
    ubicacion: "Estado de México",
    contrato: "Tiempo completo",
    jornada: "Mixta",
    salario: 10000,
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    desc: "Control de inventarios, recepción y despacho de mercancía, manejo de montacargas.",
    tags: ["Inventarios", "Montacargas", "Logística"],
    responsabilidades: [
      "Recepción, clasificación y despacho de mercancía",
      "Control y actualización de inventarios en sistema",
      "Operación de montacargas y equipo de carga",
      "Verificación de condiciones de almacenamiento",
      "Elaboración de reportes de entradas y salidas",
    ],
    requisitos: [
      "Secundaria terminada (preparatoria deseable)",
      "Licencia de montacargas vigente",
      "Experiencia mínima de 1 año en almacén o logística",
      "Capacidad para cargar hasta 25 kg",
      "Disponibilidad para jornada mixta",
    ],
  },
  {
    id: 3,
    titulo: "Ejecutivo de Ventas",
    empresa: "Sigma Retail",
    categoria: "Ventas",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 18000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Prospección, seguimiento y cierre de ventas B2B. Manejo de CRM y cumplimiento de metas.",
    tags: ["Ventas B2B", "CRM", "Negociación"],
    responsabilidades: [
      "Prospección y generación de nuevos clientes B2B",
      "Seguimiento puntual a oportunidades de venta",
      "Cierre de negociaciones y elaboración de propuestas",
      "Mantenimiento y actualización del CRM",
      "Cumplimiento de metas mensuales de venta",
    ],
    requisitos: [
      "Licenciatura en Administración, Mercadotecnia o afín",
      "Experiencia mínima de 2 años en ventas B2B",
      "Manejo de CRM (HubSpot, Salesforce o similar)",
      "Habilidades de negociación y comunicación",
      "Auto propio (deseable)",
    ],
  },
  {
    id: 4,
    titulo: "Recepcionista",
    empresa: "Clínica Vitalis",
    categoria: "Atención al cliente",
    ubicacion: "CDMX",
    contrato: "Medio tiempo",
    jornada: "Vespertina",
    salario: 8000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Atención presencial y telefónica, coordinación de citas y gestión de correspondencia.",
    tags: ["Atención al cliente", "Multitareas", "Comunicación"],
    responsabilidades: [
      "Atención presencial y telefónica a pacientes y visitantes",
      "Coordinación y agendamiento de citas médicas",
      "Gestión de correspondencia y paquetería",
      "Mantenimiento del área de recepción en orden",
      "Apoyo administrativo al equipo médico",
    ],
    requisitos: [
      "Preparatoria terminada",
      "Excelente presentación y trato al público",
      "Experiencia mínima de 6 meses en recepción o atención al cliente",
      "Manejo básico de herramientas de oficina",
      "Disponibilidad en horario vespertino (14:00 a 20:00)",
    ],
  },
  {
    id: 5,
    titulo: "Coordinador de RRHH",
    empresa: "Grupo Corpora",
    categoria: "RRHH",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 22000,
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    desc: "Gestión de nómina, reclutamiento, capacitación y relaciones laborales en empresa en crecimiento.",
    tags: ["Nómina", "Reclutamiento", "Relaciones laborales"],
    responsabilidades: [
      "Administración y procesamiento de nómina quincenal",
      "Reclutamiento y selección de personal operativo y administrativo",
      "Diseño e implementación de programas de capacitación",
      "Gestión de relaciones laborales y clima organizacional",
      "Cumplimiento de obligaciones legales laborales (IMSS, INFONAVIT, SAT)",
    ],
    requisitos: [
      "Licenciatura en Administración, Psicología o Relaciones Industriales",
      "Experiencia mínima de 3 años en puesto similar",
      "Conocimiento de Ley Federal del Trabajo y normatividad laboral",
      "Manejo de sistemas de nómina (NOI, SUA o similar)",
      "Liderazgo, organización y comunicación efectiva",
    ],
  },
  {
    id: 6,
    titulo: "Vendedor de Campo",
    empresa: "Sigma Retail",
    categoria: "Ventas",
    ubicacion: "Estado de México",
    contrato: "Tiempo completo",
    jornada: "Flexible",
    salario: 15000,
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    desc: "Visitas a clientes, presentación de productos y seguimiento posventa en zona Edomex.",
    tags: ["Ventas externas", "Zona Edomex", "Prospectos"],
    responsabilidades: [
      "Visitas programadas a clientes actuales y prospectos",
      "Presentación y demostración de productos en punto de venta",
      "Levantamiento de pedidos y seguimiento posventa",
      "Cobertura de ruta asignada en zona Estado de México",
      "Reporte diario de actividades y resultados",
    ],
    requisitos: [
      "Preparatoria terminada (licenciatura deseable)",
      "Experiencia mínima de 1 año en ventas de campo o ruta",
      "Licencia de conducir vigente y auto propio",
      "Conocimiento de la zona Estado de México",
      "Disponibilidad para horario flexible y trabajo en campo",
    ],
  },
  {
    id: 7,
    titulo: "Auxiliar Contable",
    empresa: "Finanzas MX",
    categoria: "Administrativo",
    ubicacion: "Híbrido",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    salario: 13000,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Registro de operaciones contables, conciliaciones bancarias y elaboración de reportes financieros.",
    tags: ["Contabilidad", "SAP", "Excel avanzado"],
    responsabilidades: [
      "Registro de pólizas contables y operaciones diarias",
      "Conciliaciones bancarias mensuales",
      "Elaboración de reportes financieros y estados de cuenta",
      "Apoyo en declaraciones fiscales y cierre mensual",
      "Archivo y organización de documentación contable",
    ],
    requisitos: [
      "Licenciatura en Contaduría o Finanzas (pasante o titulado)",
      "Manejo intermedio-avanzado de Excel",
      "Experiencia con SAP, CONTPAQi o sistema contable similar",
      "Experiencia mínima de 1 año en área contable",
      "Conocimientos básicos de normatividad fiscal mexicana",
    ],
  },
  {
    id: 8,
    titulo: "Agente de Servicio al Cliente",
    empresa: "Contact Nova",
    categoria: "Atención al cliente",
    ubicacion: "Remoto",
    contrato: "Por proyecto",
    jornada: "Flexible",
    salario: 9500,
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    desc: "Atención a clientes vía chat, correo y teléfono. Resolución de incidencias y seguimiento de casos.",
    tags: ["Zendesk", "Servicio al cliente", "Remoto"],
    responsabilidades: [
      "Atención a clientes por chat, correo electrónico y teléfono",
      "Resolución de incidencias y quejas en primer contacto",
      "Seguimiento y documentación de casos en Zendesk",
      "Escalamiento de casos complejos al área correspondiente",
      "Cumplimiento de métricas de calidad y tiempo de respuesta",
    ],
    requisitos: [
      "Preparatoria terminada",
      "Experiencia mínima de 6 meses en atención al cliente o call center",
      "Manejo básico de Zendesk o plataforma de tickets (deseable)",
      "Buena redacción y comunicación verbal",
      "Equipo de cómputo propio y conexión a internet estable",
    ],
  },
];

export function getJobById(id: number): Job | undefined {
  return JOBS.find((j) => j.id === id);
}
