export interface Job {
  slug: string;
  titulo: string;
  categoria: string;
  ubicacion: string;
  contrato: string;
  jornada: string;
  badge: string;
  badgeClass: string;
  publicado: string;
  descripcion: string;
  responsabilidades: string[];
  requisitos: string[];
  habilidades: string[];
  beneficios: string[];
  contactEmail: string;
}

export const JOBS: Job[] = [
  {
    slug: "auxiliar-administrativo",
    titulo: "Auxiliar Administrativo",
    categoria: "Administrativo",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    publicado: "Publicado hoy",
    descripcion: "Estamos buscando un Auxiliar Administrativo organizado y proactivo para apoyar en la gestion documental, atencion a clientes internos y manejo de agenda ejecutiva. Formaras parte de un equipo dinamico con oportunidades reales de crecimiento profesional.",
    responsabilidades: [
      "Gestion documental fisica y digital de la empresa",
      "Atencion a clientes internos y externos via telefono y correo",
      "Manejo de agenda ejecutiva y coordinacion de reuniones",
      "Apoyo en procesos de facturacion y cobranza",
      "Elaboracion de reportes y presentaciones en Office 365",
    ],
    requisitos: [
      "Bachillerato concluido o carrera tecnica en curso",
      "Minimo 1 año de experiencia en puestos similares",
      "Manejo intermedio-avanzado de Office 365",
      "Excelente ortografia y redaccion",
      "Disponibilidad de horario matutino",
    ],
    habilidades: ["Office 365", "Atencion al cliente", "Organizacion", "Comunicacion"],
    beneficios: [
      "Prestaciones de ley desde el primer dia",
      "Capacitacion continua",
      "Ambiente laboral colaborativo",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "operador-almacen",
    titulo: "Operador de Almacen",
    categoria: "Operaciones",
    ubicacion: "Estado de Mexico",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    publicado: "Publicado hoy",
    descripcion: "Se solicita Operador de Almacen responsable del control de inventarios, recepcion y despacho de mercancia. Buscamos personas comprometidas, ordenadas y con capacidad de trabajo en equipo en un ambiente dinamico.",
    responsabilidades: [
      "Recepcion, acomodo y despacho de mercancia",
      "Control de inventarios y conteo ciclico",
      "Manejo de montacargas y equipo de carga",
      "Registro de entradas y salidas en sistema",
      "Cumplimiento de normas de seguridad e higiene",
    ],
    requisitos: [
      "Secundaria o bachillerato concluido",
      "Licencia vigente para operar montacargas (deseable)",
      "Experiencia minima de 1 año en almacen o logistica",
      "Disponibilidad de traslado a Estado de Mexico",
      "Buena condicion fisica",
    ],
    habilidades: ["Inventarios", "Montacargas", "Logistica", "Trabajo en equipo"],
    beneficios: [
      "Vales de despensa",
      "Transporte de personal",
      "Prestaciones de ley",
      "Comedor subsidiado",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "ejecutivo-ventas",
    titulo: "Ejecutivo de Ventas",
    categoria: "Ventas",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    publicado: "Publicado hoy",
    descripcion: "Buscamos Ejecutivo de Ventas con experiencia en prospeccion, seguimiento y cierre de ventas B2B. Te integraras a un equipo comercial con metas claras y comision atractiva.",
    responsabilidades: [
      "Prospeccion de clientes nuevos y seguimiento a cartera",
      "Presentacion de productos y servicios a tomadores de decision",
      "Manejo y actualizacion de CRM",
      "Cumplimiento de cuotas mensuales y trimestrales",
      "Negociacion y cierre de contratos",
    ],
    requisitos: [
      "Licenciatura en Administracion, Mercadotecnia o afin (truncada aceptable)",
      "Minimo 2 años de experiencia en ventas B2B",
      "Manejo de CRM (HubSpot, Salesforce o similar)",
      "Habilidades de negociacion y comunicacion",
      "Orientacion a resultados",
    ],
    habilidades: ["Ventas B2B", "CRM", "Negociacion", "Prospeccion"],
    beneficios: [
      "Sueldo base + comisiones sin tope",
      "Bonos trimestrales",
      "Capacitacion constante",
      "Plan de crecimiento",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "recepcionista",
    titulo: "Recepcionista",
    categoria: "Atencion al cliente",
    ubicacion: "CDMX",
    contrato: "Medio tiempo",
    jornada: "Matutina",
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    publicado: "Publicado hoy",
    descripcion: "Se busca Recepcionista con excelente presentacion y trato al cliente, responsable de la atencion presencial y telefonica, coordinacion de citas y gestion de correspondencia.",
    responsabilidades: [
      "Atencion presencial a visitantes y clientes",
      "Manejo de conmutador y transferencia de llamadas",
      "Coordinacion de citas y reuniones",
      "Gestion de correspondencia y paqueteria",
      "Apoyo administrativo general",
    ],
    requisitos: [
      "Bachillerato concluido",
      "6 meses a 1 año de experiencia en recepcion",
      "Excelente presentacion y trato al publico",
      "Manejo basico de Office",
      "Disponibilidad de medio tiempo matutino",
    ],
    habilidades: ["Atencion al cliente", "Multitareas", "Comunicacion", "Office"],
    beneficios: [
      "Prestaciones de ley",
      "Horario flexible",
      "Ambiente laboral agradable",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "coordinador-rrhh",
    titulo: "Coordinador de RRHH",
    categoria: "RRHH",
    ubicacion: "CDMX",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Nuevo",
    badgeClass: "bg-green-soft text-[#15803d]",
    publicado: "Publicado hoy",
    descripcion: "Buscamos Coordinador de RRHH para liderar los procesos de nomina, reclutamiento, capacitacion y relaciones laborales en empresa en crecimiento.",
    responsabilidades: [
      "Gestion completa de nomina semanal y quincenal",
      "Reclutamiento y seleccion de personal operativo y administrativo",
      "Coordinacion de programas de capacitacion",
      "Manejo de relaciones laborales y conflictos",
      "Cumplimiento de normatividad laboral vigente",
    ],
    requisitos: [
      "Licenciatura en Administracion, Psicologia o RRHH",
      "Minimo 3 años de experiencia en posiciones similares",
      "Conocimiento solido de LFT, IMSS e INFONAVIT",
      "Experiencia en manejo de nomina (NOI, CONTPAQ o similar)",
      "Liderazgo y habilidades de comunicacion",
    ],
    habilidades: ["Nomina", "Reclutamiento", "Relaciones laborales", "LFT"],
    beneficios: [
      "Sueldo competitivo",
      "Prestaciones superiores a la ley",
      "Seguro de gastos medicos",
      "Desarrollo profesional",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "vendedor-campo",
    titulo: "Vendedor de Campo",
    categoria: "Ventas",
    ubicacion: "Estado de Mexico",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Urgente",
    badgeClass: "bg-yellow-soft text-[#b45309]",
    publicado: "Publicado hoy",
    descripcion: "Se busca Vendedor de Campo con disponibilidad para visitas a clientes en zona Edomex. Responsable de presentar productos, levantar pedidos y dar seguimiento posventa.",
    responsabilidades: [
      "Visitas programadas a clientes establecidos",
      "Prospeccion de nuevos clientes en ruta asignada",
      "Levantamiento de pedidos y seguimiento de entrega",
      "Cobranza y recuperacion de cartera",
      "Reporte diario de actividades",
    ],
    requisitos: [
      "Bachillerato o carrera tecnica",
      "Licencia de conducir vigente",
      "Experiencia en ventas externas (mas de 1 año)",
      "Conocimiento de zona Edomex",
      "Auto propio (deseable)",
    ],
    habilidades: ["Ventas externas", "Prospeccion", "Cobranza", "Manejo"],
    beneficios: [
      "Sueldo base + comisiones",
      "Apoyo de gasolina y mantenimiento",
      "Celular corporativo",
      "Prestaciones de ley",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "auxiliar-contable",
    titulo: "Auxiliar Contable",
    categoria: "Administrativo",
    ubicacion: "Hibrido",
    contrato: "Tiempo completo",
    jornada: "Matutina",
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    publicado: "Publicado hoy",
    descripcion: "Se solicita Auxiliar Contable para el registro de operaciones contables, conciliaciones bancarias y elaboracion de reportes financieros en esquema hibrido.",
    responsabilidades: [
      "Registro de polizas contables diarias",
      "Conciliaciones bancarias mensuales",
      "Elaboracion de reportes financieros",
      "Apoyo en cierre mensual y anual",
      "Atencion a auditorias internas",
    ],
    requisitos: [
      "Licenciatura en Contaduria (truncada aceptable desde 7mo semestre)",
      "Manejo de SAP o ContPAQ",
      "Excel avanzado (tablas dinamicas, buscarv, etc.)",
      "Experiencia minima de 1 año",
      "Disponibilidad para esquema hibrido",
    ],
    habilidades: ["Contabilidad", "SAP", "Excel avanzado", "Conciliaciones"],
    beneficios: [
      "Esquema hibrido (3 dias oficina / 2 home office)",
      "Vales de despensa",
      "Caja de ahorro",
      "Prestaciones superiores",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
  {
    slug: "agente-servicio-cliente",
    titulo: "Agente de Servicio al Cliente",
    categoria: "Atencion al cliente",
    ubicacion: "Remoto",
    contrato: "Por proyecto",
    jornada: "Vespertina",
    badge: "Disponible",
    badgeClass: "bg-blue-soft text-blue",
    publicado: "Publicado hoy",
    descripcion: "Buscamos Agente de Servicio al Cliente para atencion via chat, correo y telefono en esquema 100% remoto. Responsable de resolver incidencias y dar seguimiento a casos.",
    responsabilidades: [
      "Atencion a clientes via chat, correo y telefono",
      "Resolucion de incidencias en primer contacto",
      "Registro y seguimiento de casos en Zendesk",
      "Escalamiento a areas especializadas cuando aplique",
      "Cumplimiento de KPIs de servicio",
    ],
    requisitos: [
      "Bachillerato concluido",
      "Experiencia en servicio al cliente (6 meses+)",
      "Manejo de Zendesk u otra herramienta de tickets",
      "Excelente ortografia y redaccion",
      "Equipo propio con internet estable",
    ],
    habilidades: ["Zendesk", "Servicio al cliente", "Remoto", "Multitareas"],
    beneficios: [
      "100% remoto",
      "Equipo incluido despues de 3 meses",
      "Bonos por desempeño",
      "Horario vespertino flexible",
    ],
    contactEmail: "reclutamiento@kyoszen.com",
  },
];

export function getJobBySlug(slug: string): Job | undefined {
  return JOBS.find((j) => j.slug === slug);
}
