// CRM Database types - Phase 2
// These types will be auto-generated by Supabase CLI once the database is set up.
// For now, they serve as a blueprint for the CRM schema.

export interface Database {
  public: {
    Tables: {
      candidates: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          status: "nuevo" | "en_proceso" | "colocado" | "descartado";
          position_applied: string | null;
          documents_complete: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["candidates"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["candidates"]["Insert"]>;
      };
      companies: {
        Row: {
          id: string;
          name: string;
          contact_name: string;
          email: string;
          phone: string | null;
          industry: string | null;
          size: "micro" | "pequeña" | "mediana" | "grande";
          location: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["companies"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["companies"]["Insert"]>;
      };
      vacancies: {
        Row: {
          id: string;
          company_id: string;
          title: string;
          category: string;
          location: string;
          contract_type: string;
          salary_min: number | null;
          salary_max: number | null;
          description: string;
          requirements: string[];
          status: "abierta" | "en_proceso" | "cerrada" | "cancelada";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["vacancies"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["vacancies"]["Insert"]>;
      };
      courses: {
        Row: {
          id: string;
          title: string;
          category: string;
          description: string;
          hours: number;
          modality: "presencial" | "en_linea" | "hibrido";
          instructor: string | null;
          price: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["courses"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["courses"]["Insert"]>;
      };
      enrollments: {
        Row: {
          id: string;
          course_id: string;
          candidate_id: string | null;
          company_id: string | null;
          status: "inscrito" | "en_curso" | "completado" | "cancelado";
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["enrollments"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["enrollments"]["Insert"]>;
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          subject: string;
          message: string;
          status: "nuevo" | "leido" | "respondido";
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["contact_submissions"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["contact_submissions"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
